# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       heliumreborn

# >> macros
# << macros

Summary:    Helium Mobile browser ported to MeeGo Qt Quick Components
Version:    1.1.4
Release:    1
Group:      System/Libraries
License:    LGPL v2.1
URL:        https://github.com/nemomobile/heliumreborn
Source0:    %{name}-%{version}.tar.bz2
Source100:  heliumreborn.yaml
Requires:   /usr/bin/update-desktop-database
Requires:   libqtwebkit-qmlwebkitplugin
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5OpenGL)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(Qt5Declarative)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
#BuildRequires:  pkgconfig(qt5-qtqml-import-webkitplugin)
BuildRequires:  desktop-file-utils

%description
Helium Mobile browser ported to Qt Quick Components for Nemo Mobile.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
#/usr/share/heliumreborn/main.qml
#/usr/share/heliumreborn/qml
#/usr/share/heliumreborn/qml/*.qml
#/usr/share/heliumreborn/qml/common
#/usr/share/heliumreborn/qml/common/*.qml
#/usr/share/heliumreborn/qml/LogbookViewComponents
#/usr/share/heliumreborn/qml/LogbookViewComponents/*.qml
#/usr/share/heliumreborn/pics
#/usr/share/heliumreborn/pics/*.png
#/usr/bin/heliumreborn
/usr/bin
#/usr/share/applications/heliumreborn.desktop
/usr/share/heliumreborn
/usr/share/applications
# >> files
# << files
